### ISSUE TITLE
Return data.frame() object

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#12]
I'd like to propose to return a data.frame object from all functions. Internally we can still use `tibble` or `data.table` as necessary but I like to be as generic as possible with things so things like CSV files and just plain `data.frames()` are my preference. End users can transform to a `tibble` or `data.table` as desired, IMO.

I've updated the functions in the Devel branch to return `data.frame`. If this is OK with you, @HughParsonage, I'll merge into master later.

**Comment by HughParsonage** [comment]
No problem.

**Comment by adamhsparks** [comment]
Great, thanks

**Comment by adamhsparks** [comment]
`get_current_weather()` returns a `data.table` again.

**Comment by HughParsonage** [comment]
I can't reproduce:

```
library(data.table)
library(bomrang)
is.data.table(get_current_weather("Surat"))
# [1] FALSE
```

**Comment by adamhsparks** [comment]
You're right. Not sure what I had going on. I think the repository on this computer was not updated perhaps. Sorry about that.
