### ISSUE TITLE
Prepping for submission to rOpenSci onboarding

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#14]
This package will be submitted for code review through the [rOpenSci onboarding process](https://github.com/ropensci/onboarding) and publication in the [Journal of Open Source Software](http://joss.theoj.org). 

A part of the requirements for the JOSS submission are the authors' [ORCIDs](https://orcid.org). @Keith-Pembleton and I have already entered our ORCIDs and affiliations in the [paper.md](https://github.com/ToowoombaTrio/bomrang/blob/master/inst/paper/paper.md) file. 

@HughParsonage, I've added the sections for you fill in, affiliation and ORCID, if you wish to be listed in the package citation, please. I'm not sure if citations are important for you, but they certainly are for Keith and me as academics, so this [paper](https://github.com/ToowoombaTrio/bomrang/blob/master/inst/paper/paper.md) will be the official citation for the package.

**Comment by HughParsonage** [comment]
I've added my ORCID.

**Comment by adamhsparks** [comment]
Thanks Hugh

**Comment by adamhsparks** [comment]
@HughParsonage, do you intend to not provide an affiliation? Just checking.

**Comment by HughParsonage** [comment]
Hi, thanks, I had overlooked that.

**Comment by adamhsparks** [comment]
thanks
