### ISSUE TITLE
JSONurl_latlon_by_station_name and stations_meta in get_ag_bulletin() are the same

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#15]
Use just `JSONurl_latlon_by_station_name` that's been cleaned for the most recent data as demonstrated by @HughParsonage in https://github.com/ToowoombaTrio/bomrang/blob/master/data-raw/get_bom_stations.R

Some of the initial data fetching can be streamlined using the code from `get_ag_bulletin()`, lines 69-84.

Once this is done, save database internally and use for both `get_current_weather()` and `get_ag_bulletin()` functions to cut down on code and time necessary to run functions.

**Comment by adamhsparks** [comment]
I think that this can be turned into a single function that runs for both incorporating the ability to select only current stations using the system date rather than hard coding the value. It's pretty quick to run and fetch the results and this circumvents the need to update an internal database.

We still need a list of station urls, this gist may help, https://github.com/njtierney/bomr/blob/master/R/rudis-gist.R

**Comment by adamhsparks** [comment]
@HughParsonage, please have a look at this document I've put together and let me know your thoughts, can we use this as a replacement for your method of generating the JSON urls?

I think I've figured out the methodology BOM uses to generate the URLs, it's the product ID code number 60901 (all weather observations) and the WMO number for the station.

This is much faster than generating all numbers and checking the website and results in more URLs.

https://github.com/ToowoombaTrio/bomrang/blob/devel/data-raw/create_BOM_station_list.md

**Comment by HughParsonage** [comment]
Hahaha! Yes, that's much better. Mine was stupid but worked. But it was stupid.

I would add a test to make sure the number of stations exceed a known number and that certain stations are included.

**Comment by adamhsparks** [comment]
OK, thanks. I'll write some tests for it.

I'm thinking about having this run on package load to get the latest station data. I'll see how much time it really adds to the package doing this. Alternatively, I'm thinking of putting a timestamp in the data and checking that and then automatically refreshing it monthly on package load. Does that make sense? Is it rubbish?

**Comment by adamhsparks** [comment]
Scratch that previous idea. I'm just rolling it into the internal_functions.R file and will call a function to download the metadata when the `get_current_weather()` or `get_ag_bulletin()` is called. It only takes a second or two to run and it means we don't have to worry about continually updating the package after it's distributed.

**Comment by adamhsparks** [comment]
Mostly finished now. I've had to make some modifications to `sweep_for_stations()` and `get_current_weather()` to work with the new functionality.

One of the biggest is that the check for lat/lon failed because there are stations that are now returned. Norfolk Island and Mawson (Antarctica).

I need to run a check on all the URLs to make sure that they are valid. If not, I'll need to think about how to handle those requests. Perhaps on-the-fly in the `get_current_weather()` function, check and if a station is requested that returns a 404 we return an error message. This is quicker/easier than checking all as the URLs are created. I've weeded out many of the non-existent URLs, where there is a current station with a  WMO, most of these don't have a "state" value.

**Comment by adamhsparks** [comment]
I think that this code block should work, so no need to do anything else regarding previous comment.

`r
   if ("observations" %notin% names(observations.json) ||
        "data" %notin% names(observations.json$observations)) {
      stop("A station was matched but the JSON returned by bom.gov.au was not in expected form.")
`

**Comment by adamhsparks** [comment]
Finalised in Devel branch. Testing now, ready to merge with Master pending comment and last bits of testing.

@HughParsonage if you have time to look and make comments. I've had to modify your code a bit to make this work, but I think we're good to go now.

**Comment by HughParsonage** [comment]
If you open a pull-request I can review it in its entirety (or a subset).

**Comment by adamhsparks** [comment]
Good idea, see https://github.com/ToowoombaTrio/bomrang/pull/18

**Comment by adamhsparks** [comment]
Closed with https://github.com/ToowoombaTrio/bomrang/commit/8b729bd11474ead0e238b29391b7df13f9ef333d
