### ISSUE TITLE
jsonlite preferred over rjson

### ISSUE THREAD

**Issue by HughParsonage** [ToowoombaTrio/bomrang#19]
I chose `library(rjson)` arbitrarily but it seems `jsonlite` is explicitly preferred by rOpenSci (https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#tools) and they're probably right.

**Comment by adamhsparks** [comment]
OK. Thanks, I'll update the review request with this issue so they know we're addressing it.

**Comment by adamhsparks** [comment]
thanks.
