### ISSUE TITLE
Return stations_site_list as a data frame

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#31]
Renamed after discussion below.

Will simply ensure that `stations_site_list` is a data.frame and that all functions include option to return `data.table` object as `get_current_weather()` now does.

---------------------------------------------------------

From @mpadge in https://github.com/ropensci/onboarding/issues/121

> All functions perform as described and intended, and the data.frame tidying is exemplary. Given the amount of work the Toowoomba Trio (also a great name, by the way!) put into tidying, I wonder whether it might not be worth while returning all data.frame objects as tibble objects? This would offer a couple of distinct advantages:

> Many functions, such as get_precis_forecast(), return very large dfs. Naively examining these quickly fills the screen with junk, and requires a doubling of much code in the vignette such as,
`QLD_forecast <- get_precis_forecast(state = "QLD")`
`head(QLD_forecast)`
>If it were a tibble, it would suffice to simply have,
`get_precis_forecast(state = "QLD")`
>At the moment,
`class (stations_site_list)`
`# [1] "tbl_df"     "tbl"        "data.frame"`
> yet all other objects are data.frame objects. I suspect this particular data is worth keeping in data/ (rather than inst/data), yet having one tibble and data.frame objects for everything else is perhaps inconsistent (even untidy, one might assert).

**Comment by adamhsparks** [comment]
@HughParsonage, I'm thinking this is OK to do, especially with the whole tidyverse and the fact that we do return a tidy data frame.

Looking at `get_current_weather()` gives me the idea to offer the default return as a `tibble` but optionally return a `data.table` for the other objects that `bomrang` returns.

Thoughts?

**Comment by HughParsonage** [comment]
I'm quite OK with either `tibbles` or `data.frames` by default (I'd personally use `data.table`.) 

If we both had infinite time and will, I think the 'correct' way to do would be provide an option `options("bomrang.print.method" = "tibble")` and let the user's preference dictate the print method. 

But it seems to be a mostly cosmetic criticism of the package. Feel free to assign me work if you'd prefer me to do it.

**Comment by adamhsparks** [comment]
Yeah, it does seem mostly cosmetic. I'm still on the fence. However, if nothing else we should make sure the package is standardised, `stations_site_list` is a `tibble` at the moment.

I'd initially settled on using `data.frame` just for the end user to make the call thinking that someone who wanted a tibble would know how to use `foo <- as_tibble(get_ag_bulletin(state = "Qld"))` and could make that call themselves.

I'm happy to return a `data.frame` and offer `data.table` as an option for all the returns for consistency across the package.

**Comment by mpadge** [comment]
My two cents worth: I see it really just as a cosmetic decision, and the review comment was really just about inconsistency given the package claim to return a "tidy data frame" of everything. It seems fair to expect "tidy" to mean consistent. Easiest path would just be converting the current sole `tibble` to a simple `data.frame` and job would be done. `tibble`-ifying everything does have the further disadvantage that the `print` method truncates full view to (usually) 5 columns only, whereas `print` for `data.frame`s at least lets you see all columns.

**Comment by adamhsparks** [comment]
Thanks @mpadge, I think we're on the same page then fro your post and my
last.

I'll detibble the lone tibble and we should offer the same options in all
functions, i.e. to return a data.frame as well



-- 
Adam H Sparks

**Comment by adamhsparks** [comment]
For consistency, should we make `JSONurl_latlon_by_station_name` a `data.frame` object as well and convert it to a `data.table` object in the functions when fetching current weather?

**Comment by mpadge** [comment]
But wouldn't this be better as internal data? Then it doesn't really matter what it is. No user is ever going to need to access that, right?

**Comment by adamhsparks** [comment]
@mpadge, @HughParsonage  and I discussed exposing the data externally here:
https://github.com/ToowoombaTrio/bomrang/issues/23

We decided to leave data exposed. I can see possible use cases similar to what Hugh already described there, for myself as well. It also means that you can update only one data set at a time. If it's internal it's all one Rda file, unless I'm mistaken?

**Comment by HughParsonage** [comment]
> But it seems to be a mostly cosmetic criticism of the package. Feel free to assign me work if you'd prefer me to do it.

**Comment by adamhsparks** [comment]
I've come around and agree with @mpadge. There's no need to pollute the user-space with the data. I've started moving the data to be internal only. Two of the three databases currently are internal only. I'll update the third shortly.

If someone really wants the data, they can refer to the Rmd files in /data-raw https://github.com/ToowoombaTrio/bomrang/tree/devel/data-raw to create their own.

**Comment by adamhsparks** [comment]
Closed with https://github.com/ToowoombaTrio/bomrang/commit/d9f13cbe73f840f787b941e70e67e10f782a9a68
