### ISSUE TITLE
Default argument NULL should be reserved for optional arguments

### ISSUE THREAD

**Issue by HughParsonage** [ToowoombaTrio/bomrang#33]
Per http://adv-r.had.co.nz/Functions.html

>Sometimes you want to add a non-trivial default value, which might take several lines of code to compute. Instead of inserting that code in the function definition, you could use missing() to conditionally compute it if needed. However, this makes it hard to know which arguments are required and which are optional without carefully reading the documentation. Instead, I usually set the default value to NULL and use is.null() to check if the argument was supplied.

I believe this is now conventional usage: if a function is defined with `function(arg = NULL)` then `arg` is understood to be optional. 

Yet for example 

```r
get_ag_bulletin <- function(state = NULL) {
```

I think this should be just

```r
get_ag_bulletin <- function(state) {

if (missing(state)) {
  stop("Please provide a valid 2 or 3 letter state or territory postal code abbreviation.")
}
...
```
(so that it's clear that `state` needs to be supplied by the user), **or** `get_ag_bulletin()` should return something sensible (such as the bulletin for *all* states) by default.

**Comment by adamhsparks** [comment]
Thanks Hugh. I'll get on that!

**Comment by adamhsparks** [comment]
Closed with: https://github.com/ToowoombaTrio/bomrang/commit/0b7deffd8d89bad947816091f688ed21c09e4047
