### ISSUE TITLE
Rename JSONurl_latlon_by_station_name to be shorter

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#38]
> JSONurl_latlon_by_station_name is a very long variable name

This has been raised by both reviewers. 

https://github.com/ropensci/onboarding/issues/121#issuecomment-315419598

**Comment by adamhsparks** [comment]
Any thoughts on renaming this? I agree it's long, but it's not something the end user ever interacts with.

**Comment by adamhsparks** [comment]
@HughParsonage, shall I modify the variable name, are you going to or are you opposed to changing it?

**Comment by HughParsonage** [comment]
Hi sorry I'm overseas so can't use GitHub. Whatever you think is best -- no
strong objections here.

**Comment by adamhsparks** [comment]
Thanks Hugh. I'll shorten it down.

Safe travels.

-- 
Adam H Sparks

**Comment by adamhsparks** [comment]
Closed with https://github.com/ToowoombaTrio/bomrang/commit/8bcba0b4c01bcc7410721e285a962f85c87d5200
