### ISSUE TITLE
Define cook and .get_obs outside functions

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#41]
I don't think `.get_obs()` is a scoping issue, will have to check, but it could probably be moved to the internal_functions.R file.

> A couple of the functions (cook and .get_obs) are defined within other functions. Is this for some scoping-related reason? Otherwise, it might make the code a bit more readable to define them outside of other functions.

https://github.com/ropensci/onboarding/issues/121#issuecomment-315419598

**Comment by HughParsonage** [comment]
I thought it was more readable to put them inside the other functions!

**Comment by adamhsparks** [comment]
I'm opening issues for discussion, we don't have to accept everything proposed during the review if it really isn't necessary or beneficial.

It's worth a look at least for mine, I think, if nothing else to ensure consistency in how the internally used functions are handled.

**Comment by adamhsparks** [comment]
I've moved `.get_obs()` outside the main function, `get_ag_bulletin()`, but left it in the same .R file since it's only used in one function and not across the package.

For me, at least, it does help to have it outside the main function I can read that more easily.

I'll close this now and we'll leave the `cook()` function as-is.
