### ISSUE TITLE
The recommended station_name values are not separated by spaces

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#43]
Both reviewers raised this issue. When suggested stations are returned in the message, there is no space between the values in the message.

**Comment by HughParsonage** [comment]
Can you provide a reprex? I can't reproduce.

**Comment by adamhsparks** [comment]
Sorry, I was just copying and pasting this morning from the reviews. I see that it's been fixed.

At any rate it's good to have a record of it here I suppose.

Thanks.
