### ISSUE TITLE
Check if server is responding

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#5]
Had some issues with the server not responding this morning. Should build in a check to see if it's responding and handle it gracefully if not.

**Comment by HughParsonage** [comment]
Which server?

Something like this would be reasonable.

```r
url_ok <- function(url) {
  url_status <- status_code(HEAD(url = url))
  identical(status_code, 200)
  # or status_code != 404
}
```

**Comment by adamhsparks** [comment]
Any of the severs we query with functions in this package.

**Comment by adamhsparks** [comment]
Brain fart. I was looking for `tryCatch()` to properly handle the FTP server not responding.

`httr::GET` won't work with FTP.

**Comment by adamhsparks** [comment]
Closed with https://github.com/ToowoombaTrio/bomrang/commit/5c2b3ddeb72bcea0af9d691e93ac398a6d98b1de
