### ISSUE TITLE
Rename current_weather() function

### ISSUE THREAD

**Issue by adamhsparks** [ToowoombaTrio/bomrang#8]
@HughParsonage, I'd like to propose to rename the `current_weather()` function to `get_current_weather()` so that it fits the function is a verb format and aligns with the other function names in the package.

Is this OK with you?

**Comment by HughParsonage** [comment]
Of course! 

That said, I deliberately chose not to use `get_current_weather`. I agree that functions should start with a verb in the imperative mood, but in my taste some verbs (like `get`, `calculate`, `do`) don't add much. That said, `get` does emphasize the HTTP retrieval.
